baseurl: "/"
languageCode: "fr-fr"
title: "Code-Troopers Conception d’applications web et mobiles sur-mesure"
archetypeDir: "site/archetypes"
contentDir: "site/content"
dataDir: "site/data"
layoutDir: "site/layouts"
staticDir: "site/static"
themesDir: "site/themes"
paginate: 9
pygmentsUseClasses: true
SectionPagesMenu: "main"
relativeURLs: true
menu:
  main:
    - Identifier: "skills"
      Name: "Compétences"
      URL: "/#skills"
      Weight: 1
    - Identifier: "portfolio"
      Name: "Réalisations"
      URL: "/#portfolio"
      Weight: 2
    - Identifier: "casting"
      Name: "Casting"
      URL: "/#casting"
      Weight: 3
    - Identifier: "team"
      Name: "Les Troopers"
      URL: "https://team.code-troopers.com"
      Weight: 4
    - Identifier: "contact"
      Name: "Contact"
      URL: "/#contact"
      Weight: 5
    - Identifier: "blog"
      Name: "Blog"
      URL: "/blog/"
      Pre: "blog"
      Weight: 6
params:
    description: Code-Troopers est une agence spécialisée dans le développement logiciel et la conception d’applications mobiles sur-mesure. Analyse pour de grands groupes, développement natif multisupport pour des start-ups innovantes… Les membres de notre structure s’engagent dans des suivis complets, rigoureux, au plus près des différentes phases de vos projets informatiques.